# Generated by Django 3.2 on 2024-02-17 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_move', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('status', models.CharField(choices=[('add', 'Добаленно'), ('move', 'Прошло')], default='новая', max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
